# create a conda env with 'conda env create -f environment.yml -prefix [path]'
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda


dependencies:
  - python=3.10 # 3.10 bugs out some dependencies
  - openms
  - pip
  - ipykernel
  - matplotlib-venn
  - pip:
    - pyprophet
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - numexpr
    - statsmodels
    - click
    - matplotlib
    - openpyxl
    - seaborn
    - venn
    - lxml
    - pridepy
    - sdrf-pipelines
    - requests
    - pyopenms
    - ppx
    # - ipython
    - pyteomics
    # - msproteomicstools
    - nbstripout


# https://gist.github.com/33eyes/431e3d432f73371509d176d0dfb95b6e
# Follow this link for notebook setup 
