[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "kardemumma"
version = "0.1.0"
description = "Key Analysis of Reproducible Data for Efficient Monitoring in Unified Mass Spectrometry Methods and Assays"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Thanadol Sutantiwanichkul", email = "khunkoei@gmail.com"},
]
license = {text = "MIT"}
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "lxml",
    "matplotlib",
    "seaborn",
    "statsmodels",
    "sdrf-pipelines[ontology]",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/thanadol-git/kardemumma"
Issue = "https://github.com/thanadol-git/kardemumma/issues"