[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "skyline-qc"
version = "0.1.0"
description = "Simple tools to clean up data from Skyline"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests",
    "pandas",
    "lxml",
    "sdrf-pipelines[ontology]",
    "matplotlib",
    "seaborn",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/thanadol-git/skyline_qc"
Issue = "https://github.com/thanadol-git/skyline_qc/issues"