[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "kardemumma"
version = "0.1.2"
description = "Key Analysis of Reproducible Data for Efficient Monitoring in Unified Mass Spectrometry Methods and Assays"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "Thanadol Sutantiwanichkul", email = "khunkoei@gmail.com"},
]
license = "MIT"
keywords = ["proteomics", "mass spectrometry", "PRM", "quality control", "batch correction"]
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "lxml",
    "matplotlib",
    "seaborn",
    "statsmodels",
    "sdrf-pipelines[ontology]",
    "matplotlib-venn",
    "scikit-learn",
    "umap-learn",
    "nbformat",
    "pyteomics",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]

[project.scripts]
kardemumma-preview = "kardemumma.cli.preview:main"
kardemumma-cutoff  = "kardemumma.cli.cutoff:main"
kardemumma-report  = "kardemumma.cli.report:main"
kardemumma-ipynb   = "kardemumma.cli.ipynb:main"
kardemumma-docs    = "kardemumma.cli.docs:main"

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/thanadol-git/kardemumma"
Issue = "https://github.com/thanadol-git/kardemumma/issues"
Changelog = "https://github.com/thanadol-git/kardemumma/releases"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]